# -*- coding: utf-8 -*-
"""Data types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvWd_G8JbB3SpHyImoytqLkUxe5t3U9S

#DATA TYPES

In Python, data types are like categories that tell the computer what kind of data you're working with. They help the computer understand how to store and manipulate the data. Some common data types include:

Integer (int): Whole numbers, like 10 or -3.

Float (float): Decimal numbers, like 3.14 or -0.001.

String (str): Text, like "Hello" or "Python".

Boolean (bool): True or False values.

Each data type has specific properties and uses, making it easier to handle different kinds of data in your programs.
"""

# Variables
x = 10
y = 3.14
name = "Alice"
is_valid = True
list_var = [1, 2, 3]
tuple_var = (4, 5, 6)
dict_var = {'a': 1, 'b': 2}

"""# Find and print data types"""

# Find and print data types

print(type(x))       # Prints: <class 'int'>
print(type(y))       # Prints: <class 'float'>
print(type(name))    # Prints: <class 'str'>
print(type(is_valid)) # Prints: <class 'bool'>
print(type(list_var)) # Prints: <class 'list'>
print(type(tuple_var)) # Prints: <class 'tuple'>
print(type(dict_var))  # Prints: <class 'dict'>
