# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jo-L3ybnUxWlr-z025_H5DkLixMPaat6

# Questions

1.Reverse Words in a Sentence:
Write a Python program that takes the string "Hello world from Python" and prints a new string where the words are in reverse order. The output should be "Python from world Hello".



2.Find the Longest Word:
Write a Python program to find the longest word in the list ["Python", "is", "a", "wonderful", "programming", "language"]. Print the longest word and its length.




3.Convert Celsius to Fahrenheit:
Given a list of temperatures in Celsius [0, 20, 37, 100], write a program to convert each temperature to Fahrenheit and store them in a new list. Use list comprehension to accomplish this.
(Hint: Formula is F = C * 9/5 + 32)
"""