# -*- coding: utf-8 -*-
"""Day2. Operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvWd_G8JbB3SpHyImoytqLkUxe5t3U9S

#OPERATORS
"""

#let

x = 10
y = 3

print(x + y)  # Addition
print(x - y)  # Subtraction
print(x * y)  # Multiplication
print(x / y)  # Division
print(x % y)  # Modulus
print(x ** y) # Exponentiation
print(x // y) # Floor division

# Comparison Operator on these two variable
print(x > y)
print(x < y)
print(x == y)
print(x != y)

#Assignment Operators
x = 5
x += y  # Equivalent to x = x + y
x -= y  # Equivalent to x = x - y
x *= y  # Equivalent to x = x * y
x /= y  # Equivalent to x = x / y
x %= y  # Equivalent to x = x % y
x **= y # Equivalent to x = x ** y
x //= y # Equivalent to x = x // y

#Logical Operators
print(x and y)  # Logical AND
print(x or y)   # Logical OR
print(not x)    # Logical NOT

#Bitwise Operators
x = 5  # binary: 0101
y = 3  # binary: 0011

print(x & y)  # Bitwise AND: 0101 & 0011 = 0001 (1)
print(x | y)  # Bitwise OR: 0101 | 0011 = 0111 (7)
print(x ^ y)  # Bitwise XOR: 0101 ^ 0011 = 0110 (6)
print(~x)     # Bitwise NOT: ~0101 = 1010 (-6 in two's complement)
print(x << y) # Bitwise left shift: 0101 << 3 = 0101000 (40)
print(x >> y) # Bitwise right shift: 0101 >> 3 = 0000 (0)

#Membership Operators

x = 5
y = [1, 2, 3, 4, 5]

print(x in y)      # True if x is in the list y
print(x not in y)  # True if x is not in the list y
