# -*- coding: utf-8 -*-
"""Day1. Variables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvWd_G8JbB3SpHyImoytqLkUxe5t3U9S

#VARIABLES

In Python, a variable is like a container that holds data. You can think of it as a label for a value. For example, when you write x = 10, you're telling Python to store the number 10 in a container named x. Later, you can use x to access the value 10. Variables make it easy to store, use, and change information in your programs.
"""

#Creating Variables

x = 10        # Integer
y = 3.14      # Float
name = "Alice"  # String
is_valid = True # Boolean

# Assign multiple variables in a single line

a, b, c = 1, 2, 3
print(a)
print(b)
print(c)